name: Full Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
     uses: ./.github/workflows/buildPages.yml
     secrets:
      envPAT: ${{secrets.envPAT}}
  call-deploy-workflow:
    needs: call-build-workflow
    uses: ./.github/workflows/static.yml
