name: Full Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
     uses: ./.github/workflows/buildPages.yml
  call-deploy-workflow:
    uses: ./.github/workflows/static.yml
